/**
 * BoyMeetsHoodLending v2 — 0x5be2edeeb3d76f1214De7ee35c52d3B9bD5f6762
 * Status enum: 0 None, 1 Active, 2 Repaid, 3 Defaulted
 */
export const lendingAbi = [
  /* ── Reads ────────────────────────────────────────────────────────────── */
  {
    type: "function",
    name: "requests",
    stateMutability: "view",
    inputs: [{ name: "requestId", type: "uint256" }],
    outputs: [
      { name: "borrower", type: "address" },
      { name: "principal", type: "uint128" },
      { name: "interestBps", type: "uint16" },
      { name: "duration", type: "uint32" },
      { name: "expiresAt", type: "uint64" },
      { name: "active", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "offers",
    stateMutability: "view",
    inputs: [{ name: "offerId", type: "uint256" }],
    outputs: [
      { name: "lender", type: "address" },
      { name: "principal", type: "uint128" },
      { name: "interestBps", type: "uint16" },
      { name: "duration", type: "uint32" },
      { name: "expiresAt", type: "uint64" },
      { name: "tokenCount", type: "uint8" },
      { name: "active", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "loans",
    stateMutability: "view",
    inputs: [{ name: "loanId", type: "uint256" }],
    outputs: [
      { name: "lender", type: "address" },
      { name: "borrower", type: "address" },
      { name: "principal", type: "uint128" },
      { name: "repayAmount", type: "uint128" },
      { name: "fee", type: "uint128" },
      { name: "startedAt", type: "uint64" },
      { name: "dueAt", type: "uint64" },
      { name: "status", type: "uint8" },
    ],
  },
  {
    type: "function",
    name: "requestTokens",
    stateMutability: "view",
    inputs: [{ name: "requestId", type: "uint256" }],
    outputs: [{ type: "uint256[]" }],
  },
  {
    type: "function",
    name: "loanTokens",
    stateMutability: "view",
    inputs: [{ name: "loanId", type: "uint256" }],
    outputs: [{ type: "uint256[]" }],
  },
  {
    type: "function",
    name: "owed",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "nextRequestId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "nextOfferId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "nextLoanId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "totalDue",
    stateMutability: "view",
    inputs: [{ name: "loanId", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "MAX_BUNDLE",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint8" }],
  },

  /* ── Borrower side ────────────────────────────────────────────────────── */
  {
    type: "function",
    name: "createRequest",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tokenIds", type: "uint256[]" },
      { name: "principal", type: "uint128" },
      { name: "interestBps", type: "uint16" },
      { name: "duration", type: "uint32" },
      { name: "expiresAt", type: "uint64" },
    ],
    outputs: [{ name: "requestId", type: "uint256" }],
  },
  {
    type: "function",
    name: "cancelRequest",
    stateMutability: "nonpayable",
    inputs: [{ name: "requestId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "takeOffer",
    stateMutability: "nonpayable",
    inputs: [
      { name: "offerId", type: "uint256" },
      { name: "tokenIds", type: "uint256[]" },
    ],
    outputs: [{ name: "loanId", type: "uint256" }],
  },
  {
    type: "function",
    name: "repay",
    stateMutability: "nonpayable",
    inputs: [{ name: "loanId", type: "uint256" }],
    outputs: [],
  },

  /* ── Lender side ──────────────────────────────────────────────────────── */
  {
    type: "function",
    name: "fundRequest",
    stateMutability: "nonpayable",
    inputs: [{ name: "requestId", type: "uint256" }],
    outputs: [{ name: "loanId", type: "uint256" }],
  },
  {
    type: "function",
    name: "createOffer",
    stateMutability: "nonpayable",
    inputs: [
      { name: "principal", type: "uint128" },
      { name: "interestBps", type: "uint16" },
      { name: "duration", type: "uint32" },
      { name: "expiresAt", type: "uint64" },
      { name: "tokenCount", type: "uint8" },
    ],
    outputs: [{ name: "offerId", type: "uint256" }],
  },
  {
    type: "function",
    name: "cancelOffer",
    stateMutability: "nonpayable",
    inputs: [{ name: "offerId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "claimDefault",
    stateMutability: "nonpayable",
    inputs: [{ name: "loanId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [{ name: "amount", type: "uint256" }],
  },
] as const;
